plugins {
    id 'java'
}

group = 'ru.inh'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    // The copied Paper server contains the API and its compile-time dependencies.
    compileOnly fileTree(dir: 'libraries', includes: ['**/*.jar'])
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

jar {
    archiveBaseName = 'MobSpawnControl'
}
