plugins {
    id 'java'
}

group = 'ru.inh'
version = '1.0.0'

dependencies {
    compileOnly fileTree(dir: '../libraries', includes: ['**/*.jar'])
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

jar {
    archiveBaseName = 'Gods'
}
